type N = {
  calories: number
  carbsG: number
  proteinG: number
  fatG: number
  sodiumMg: number
  sugarG?: number
  fiberG?: number
  saturatedFatG?: number
}

type FoodItem = {
  id: string
  name: string
  category: string
  aliases?: string[]
  pieceWeightG?: number
  servingGrams?: number
  servingLabel?: string
  per100g: N
  refinedCarbLevel?: "low" | "medium" | "high"
}

function f(
  id: string,
  name: string,
  category: string,
  pieceWeightG: number,
  servingLabel: string,
  per100g: N,
  aliases?: string[],
  refinedCarbLevel?: "low" | "medium" | "high"
): FoodItem {
  return {
    id,
    name,
    category,
    pieceWeightG,
    servingGrams: pieceWeightG,
    servingLabel,
    per100g,
    aliases,
    refinedCarbLevel,
  }
}

/** 한국 음식 확장 DB — 100g 기준 영양성분 (대략값) */
export const FOOD_DATABASE_KOREAN_EXT: FoodItem[] = [
  f("rice-nurungji", "누룽지", "곡물", 40, "1줌", { calories: 380, carbsG: 82, proteinG: 7, fatG: 2, sodiumMg: 15, fiberG: 1.5 }, ["누룽지밥","스크래치"], "high"),
  f("rice-scorched", "누릇밥", "곡물", 210, "1공기", { calories: 135, carbsG: 29, proteinG: 2.6, fatG: 0.4, sodiumMg: 5 }, ["누릇"], "high"),
  f("rice-otbokkeum", "오곡밥", "곡물", 210, "1공기", { calories: 120, carbsG: 25, proteinG: 3.5, fatG: 1, sodiumMg: 4 }, ["오곡","잡곡"], "medium"),
  f("rice-lotus-leaf", "연잎밥", "곡물", 250, "1인분", { calories: 125, carbsG: 27, proteinG: 3, fatG: 0.8, sodiumMg: 8 }, ["연잎밥"], "high"),
  f("rice-bibim-base", "비빔밥밥", "곡물", 210, "1공기", { calories: 128, carbsG: 28, proteinG: 2.5, fatG: 0.3, sodiumMg: 2 }, ["비빔밥용밥"], "high"),
  f("juk-abalone", "전복죽", "곡물", 350, "1그릇", { calories: 55, carbsG: 9, proteinG: 3.5, fatG: 1.2, sodiumMg: 280 }, ["전복죽","전복"], "medium"),
  f("juk-pumpkin", "호박죽", "곡물", 350, "1그릇", { calories: 48, carbsG: 10, proteinG: 1.2, fatG: 0.5, sodiumMg: 200 }, ["단호박죽"], "medium"),
  f("juk-red-bean", "팥죽", "곡물", 350, "1그릇", { calories: 95, carbsG: 18, proteinG: 3, fatG: 1, sodiumMg: 50, sugarG: 8 }, ["단팥죽","팥죽"], "medium"),
  f("juk-chicken", "닭죽", "곡물", 350, "1그릇", { calories: 52, carbsG: 9, proteinG: 3.5, fatG: 0.8, sodiumMg: 320 }, ["삼계죽","닭죽"], "medium"),
  f("juk-pine-nut", "잣죽", "곡물", 350, "1그릇", { calories: 75, carbsG: 11, proteinG: 2.5, fatG: 2.5, sodiumMg: 180 }, ["잣죽"], "medium"),
  f("juk-black-bean", "검은콩죽", "곡물", 350, "1그릇", { calories: 58, carbsG: 10, proteinG: 3.8, fatG: 1, sodiumMg: 150 }, ["서리태죽"], "medium"),
  f("juk-oyster", "굴죽", "곡물", 350, "1그릇", { calories: 50, carbsG: 9, proteinG: 3.2, fatG: 0.8, sodiumMg: 350 }, ["굴죽"], "medium"),
  f("juk-mushroom", "버섯죽", "곡물", 350, "1그릇", { calories: 45, carbsG: 8.5, proteinG: 2, fatG: 0.6, sodiumMg: 280 }, ["표고죽"], "medium"),
  f("juk-vegetable", "야채죽", "곡물", 350, "1그릇", { calories: 42, carbsG: 8, proteinG: 1.5, fatG: 0.5, sodiumMg: 250 }, ["채소죽"], "medium"),
  f("juk-tuna", "참치죽", "곡물", 350, "1그릇", { calories: 58, carbsG: 9, proteinG: 4.5, fatG: 1.2, sodiumMg: 400 }, ["참치죽"], "medium"),
  f("juk-sesame", "흑임자죽", "곡물", 350, "1그릇", { calories: 72, carbsG: 10, proteinG: 2.8, fatG: 2.8, sodiumMg: 120 }, ["흑임자"], "medium"),
  f("juk-beef", "소고기죽", "곡물", 350, "1그릇", { calories: 55, carbsG: 9, proteinG: 4, fatG: 1, sodiumMg: 350 }, ["쇠고기죽"], "medium"),
  f("juk-shark-fin", "상어지느러미죽", "곡물", 350, "1그릇", { calories: 48, carbsG: 8, proteinG: 2, fatG: 0.8, sodiumMg: 300 }, ["상어죽"], "medium"),
  f("rice-egg-fried", "계란볶음밥", "곡물", 350, "1그릇", { calories: 165, carbsG: 24, proteinG: 5, fatG: 5, sodiumMg: 380 }, ["계란밥","볶음밥"], "high"),
  f("rice-kimchi-fried", "김치볶음밥", "곡물", 350, "1그릇", { calories: 155, carbsG: 22, proteinG: 5, fatG: 5, sodiumMg: 450 }, ["김치밥","김치볶음밥"], "high"),
  f("tteok-bokki-rice", "가래떡(삶은)", "탄수", 100, "1인분", { calories: 130, carbsG: 30, proteinG: 2.5, fatG: 0.2, sodiumMg: 5 }, ["가래떡","떡"], "high"),
  f("tteok-slice", "떡국떡", "탄수", 80, "1조각", { calories: 140, carbsG: 32, proteinG: 2.5, fatG: 0.3, sodiumMg: 8 }, ["떡국용"], "high"),
  f("tteok-rice-flour", "쌀떡", "탄수", 50, "1조각", { calories: 230, carbsG: 52, proteinG: 3, fatG: 0.5, sodiumMg: 5 }, ["백설기","쌀떡"], "high"),
  f("tteok-injeolmi", "인절미", "탄수", 60, "1조각", { calories: 210, carbsG: 45, proteinG: 4, fatG: 2.5, sodiumMg: 10, sugarG: 8 }, ["인절미떡"], "high"),
  f("tteok-songpyeon", "송편", "탄수", 40, "1개", { calories: 200, carbsG: 44, proteinG: 3, fatG: 1.5, sodiumMg: 15 }, ["송편떡"], "high"),
  f("tteok-gyeongdan", "경단", "탄수", 30, "1개", { calories: 195, carbsG: 42, proteinG: 3, fatG: 1.8, sodiumMg: 8, sugarG: 12 }, ["경단떡"], "high"),
  f("tteok-jeolpyeon", "절편", "탄수", 40, "1조각", { calories: 185, carbsG: 40, proteinG: 3, fatG: 1.2, sodiumMg: 12 }, ["절편"], "high"),
  f("tteok-mochi-kr", "찹쌀떡", "탄수", 50, "1조각", { calories: 225, carbsG: 50, proteinG: 3, fatG: 0.8, sodiumMg: 5 }, ["찹쌀"], "high"),
  f("kalguksu", "칼국수", "탄수", 400, "1그릇", { calories: 115, carbsG: 22, proteinG: 4, fatG: 1.5, sodiumMg: 450 }, ["칼국"], "high"),
  f("kalguksu-noodle", "칼국수면(삶은)", "탄수", 200, "1인분", { calories: 130, carbsG: 26, proteinG: 4, fatG: 0.8, sodiumMg: 15 }, ["칼국수면"], "high"),
  f("janchi-guksu", "잔치국수", "탄수", 350, "1그릇", { calories: 105, carbsG: 20, proteinG: 3.5, fatG: 1.2, sodiumMg: 380 }, ["잔치국"], "high"),
  f("kongguksu", "콩국수", "탄수", 400, "1그릇", { calories: 95, carbsG: 14, proteinG: 5, fatG: 2.5, sodiumMg: 120 }, ["콩국"], "medium"),
  f("bibim-guksu", "비빔국수", "탄수", 350, "1그릇", { calories: 125, carbsG: 24, proteinG: 4, fatG: 2, sodiumMg: 420 }, ["비빔면"], "high"),
  f("milmyeon", "밀면", "탄수", 400, "1그릇", { calories: 110, carbsG: 22, proteinG: 4, fatG: 1, sodiumMg: 500 }, ["밀면","부산밀면"], "high"),
  f("naengmyeon-mul", "물냉면", "탄수", 400, "1그릇", { calories: 95, carbsG: 20, proteinG: 4, fatG: 0.8, sodiumMg: 550 }, ["물냉","냉면"], "high"),
  f("naengmyeon-bibim", "비빔냉면", "탄수", 400, "1그릇", { calories: 115, carbsG: 24, proteinG: 4.5, fatG: 1.5, sodiumMg: 480 }, ["비빔냉"], "high"),
  f("naengmyeon-hamheung", "함흥냉면", "탄수", 400, "1그릇", { calories: 105, carbsG: 21, proteinG: 4, fatG: 1.2, sodiumMg: 520 }, ["함흥"], "high"),
  f("makguksu", "막국수", "탄수", 350, "1그릇", { calories: 100, carbsG: 20, proteinG: 3.5, fatG: 0.8, sodiumMg: 400 }, ["막국"], "high"),
  f("sujebi", "수제비", "탄수", 400, "1그릇", { calories: 90, carbsG: 16, proteinG: 3, fatG: 1.5, sodiumMg: 420 }, ["수제비국"], "high"),
  f("mandu-guk", "만두국", "탄수", 400, "1그릇", { calories: 75, carbsG: 10, proteinG: 4.5, fatG: 2, sodiumMg: 550 }, ["만둣국"], "medium"),
  f("tteokguk", "떡국", "탄수", 400, "1그릇", { calories: 70, carbsG: 12, proteinG: 3, fatG: 1.5, sodiumMg: 500 }, ["떡국"], "medium"),
  f("ramyeon-dry", "비빔라면", "탄수", 120, "1봉", { calories: 420, carbsG: 65, proteinG: 9, fatG: 14, sodiumMg: 1200 }, ["비빔면"], "high"),
  f("ramyeon-jjapaghetti", "짜파게티", "탄수", 500, "1봉", { calories: 95, carbsG: 14, proteinG: 2.5, fatG: 3, sodiumMg: 550 }, ["짜파"], "high"),
  f("ramyeon-neoguri", "너구리", "탄수", 500, "1봉", { calories: 88, carbsG: 12, proteinG: 2, fatG: 3.5, sodiumMg: 600 }, ["너구리라면"], "high"),
  f("ramyeon-shin", "신라면", "탄수", 500, "1봉", { calories: 90, carbsG: 13, proteinG: 2.2, fatG: 3.8, sodiumMg: 650 }, ["신라면"], "high"),
  f("ramyeon-jin", "진라면", "탄수", 500, "1봉", { calories: 87, carbsG: 12, proteinG: 2, fatG: 3.5, sodiumMg: 620 }, ["진라면"], "high"),
  f("ramyeon-samgye", "삼양라면", "탄수", 500, "1봉", { calories: 92, carbsG: 13, proteinG: 2.3, fatG: 4, sodiumMg: 580 }, ["삼양"], "high"),
  f("jjolmyeon", "쫄면", "탄수", 350, "1그릇", { calories: 130, carbsG: 26, proteinG: 4, fatG: 1.5, sodiumMg: 480 }, ["쫄면"], "high"),
  f("cheonggukjang-guksu", "청국장국수", "탄수", 400, "1그릇", { calories: 95, carbsG: 15, proteinG: 5, fatG: 2, sodiumMg: 380 }, ["청국장면"], "medium"),
  f("udon-kr", "가락국수", "탄수", 250, "1인분", { calories: 108, carbsG: 23, proteinG: 3, fatG: 0.5, sodiumMg: 12 }, ["가락"], "high"),
  f("hoe-naengmyeon", "회냉면", "탄수", 400, "1그릇", { calories: 100, carbsG: 19, proteinG: 6, fatG: 1, sodiumMg: 480 }, ["회냉"], "high"),
  f("bungeo-ppang", "붕어빵(반죽)", "탄수", 80, "2마리", { calories: 220, carbsG: 35, proteinG: 5, fatG: 6, sodiumMg: 120 }, ["붕어빵"], "high"),
  f("hoddeok-batter", "호떡반죽", "탄수", 80, "1개", { calories: 230, carbsG: 40, proteinG: 4, fatG: 6, sodiumMg: 150 }, ["호떡"], "high"),
  f("hotteok-nut", "호떡(견과)", "탄수", 90, "1개", { calories: 245, carbsG: 38, proteinG: 5, fatG: 8, sodiumMg: 140, sugarG: 15 }, ["견과호떡"], "high"),
  f("gyeran-ppang", "계란빵", "탄수", 80, "1개", { calories: 280, carbsG: 38, proteinG: 8, fatG: 10, sodiumMg: 280 }, ["계란빵"], "high"),
  f("sora-ppang", "소라빵", "탄수", 60, "1개", { calories: 320, carbsG: 42, proteinG: 6, fatG: 14, sodiumMg: 200, sugarG: 18 }, ["소라빵"], "high"),
  f("ppang-bbang", "빵빵", "탄수", 50, "1개", { calories: 290, carbsG: 45, proteinG: 5, fatG: 9, sodiumMg: 180 }, ["붕어빵슈크림"], "high"),
  f("hodu-gwaja", "호두과자", "탄수", 40, "2개", { calories: 310, carbsG: 42, proteinG: 5, fatG: 14, sodiumMg: 120, sugarG: 20 }, ["호두과자"], "high"),
  f("bungeobbang-custard", "슈크림붕어빵", "탄수", 80, "2마리", { calories: 250, carbsG: 32, proteinG: 5, fatG: 11, sodiumMg: 130, sugarG: 12 }, ["슈붕"], "high"),
  f("patbingsu-base", "팥빙수(기본)", "탄수", 400, "1그릇", { calories: 120, carbsG: 26, proteinG: 3, fatG: 1.5, sodiumMg: 80, sugarG: 18 }, ["빙수","팥빙수"], "high"),
  f("tteok-skewer", "꼬치떡", "탄수", 80, "1꼬치", { calories: 180, carbsG: 38, proteinG: 3, fatG: 2, sodiumMg: 350 }, ["떡꼬치"], "high"),
  f("mandu-fried", "군만두", "탄수", 150, "5개", { calories: 220, carbsG: 28, proteinG: 8, fatG: 8, sodiumMg: 450 }, ["군만두","만두"], "high"),
  f("mandu-steamed", "찐만두", "탄수", 120, "5개", { calories: 180, carbsG: 26, proteinG: 7, fatG: 5, sodiumMg: 380 }, ["찐만두","물만두"], "high"),
  f("mandu-kimchi", "김치만두", "탄수", 120, "5개", { calories: 195, carbsG: 27, proteinG: 7.5, fatG: 6, sodiumMg: 420 }, ["김치만두"], "high"),
  f("mandu-meat", "고기만두", "탄수", 120, "5개", { calories: 210, carbsG: 25, proteinG: 9, fatG: 7, sodiumMg: 400 }, ["고기만두"], "high"),
  f("wonton-kr", "완탕", "탄수", 350, "1그릇", { calories: 85, carbsG: 12, proteinG: 5, fatG: 2, sodiumMg: 520 }, ["완탕면"], "high"),
  f("jjamppong-noodle", "짬뽕면(삶은)", "탄수", 200, "1인분", { calories: 125, carbsG: 25, proteinG: 4, fatG: 0.8, sodiumMg: 20 }, ["짬뽕국수"], "high"),
  f("jjajangmyeon-noodle", "짜장면(삶은)", "탄수", 200, "1인분", { calories: 135, carbsG: 27, proteinG: 4.5, fatG: 0.8, sodiumMg: 25 }, ["짜장국수"], "high"),
  f("udon-broth", "우동국물", "탄수", 300, "1그릇", { calories: 35, carbsG: 5, proteinG: 2, fatG: 0.8, sodiumMg: 650 }, ["우동국"], "medium"),
  f("kalguksu-broth", "칼국수국물", "탄수", 300, "1그릇", { calories: 40, carbsG: 5, proteinG: 2.5, fatG: 1.2, sodiumMg: 600 }, ["칼국수국"], "medium"),
  f("fruit-bokbunja", "복분자", "과일", 100, "1컵", { calories: 52, carbsG: 12, proteinG: 1.2, fatG: 0.5, sodiumMg: 2, sugarG: 8, fiberG: 6 }),
  f("fruit-omija", "오미자", "과일", 50, "10알", { calories: 45, carbsG: 11, proteinG: 0.5, fatG: 0.2, sodiumMg: 3, sugarG: 5 }),
  f("fruit-cheonggyeol", "청귤", "과일", 120, "1개", { calories: 48, carbsG: 12, proteinG: 0.8, fatG: 0.2, sodiumMg: 2, sugarG: 9 }),
  f("fruit-red-pear", "홍로배", "과일", 280, "1개", { calories: 55, carbsG: 15, proteinG: 0.4, fatG: 0.1, sodiumMg: 1, sugarG: 11 }),
  f("fruit-shingo", "신고배", "과일", 300, "1개", { calories: 54, carbsG: 14, proteinG: 0.4, fatG: 0.1, sodiumMg: 1, sugarG: 10 }),
  f("fruit-chamdarae", "참다래", "과일", 100, "1개", { calories: 61, carbsG: 15, proteinG: 1, fatG: 0.5, sodiumMg: 3, sugarG: 9 }),
  f("fruit-jujube-fresh", "대추(생)", "과일", 30, "5알", { calories: 79, carbsG: 20, proteinG: 1.2, fatG: 0.2, sodiumMg: 3, sugarG: 15 }),
  f("fruit-jujube-dried", "대추야자(건조)", "과일", 20, "5알", { calories: 287, carbsG: 73, proteinG: 3.7, fatG: 0.5, sodiumMg: 5, sugarG: 55 }),
  f("fruit-aronia", "아로니아", "과일", 100, "1컵", { calories: 47, carbsG: 10, proteinG: 1.4, fatG: 0.5, sodiumMg: 2, sugarG: 4 }),
  f("fruit-blueberry-kr", "고산블루베리", "과일", 100, "1컵", { calories: 57, carbsG: 14, proteinG: 0.7, fatG: 0.3, sodiumMg: 1, sugarG: 10 }),
  f("fruit-muscat-green", "청포도", "과일", 150, "1송이", { calories: 65, carbsG: 17, proteinG: 0.7, fatG: 0.2, sodiumMg: 2, sugarG: 15 }),
  f("fruit-apple-fuji", "후지사과", "과일", 200, "1개", { calories: 52, carbsG: 14, proteinG: 0.3, fatG: 0.2, sodiumMg: 1, sugarG: 10 }),
  f("fruit-peach-white", "백도", "과일", 150, "1개", { calories: 39, carbsG: 10, proteinG: 0.9, fatG: 0.3, sodiumMg: 0, sugarG: 8 }),
  f("fruit-plum-green", "매실", "과일", 30, "1개", { calories: 46, carbsG: 11, proteinG: 0.7, fatG: 0.3, sodiumMg: 0, sugarG: 0 }),
  f("fruit-chestnut-roasted", "군밤", "과일", 50, "5알", { calories: 245, carbsG: 53, proteinG: 3.2, fatG: 2.2, sodiumMg: 5, fiberG: 5 }),
  f("fruit-persimmon-dried-slice", "반건시", "과일", 50, "1개", { calories: 180, carbsG: 47, proteinG: 1.2, fatG: 0.3, sodiumMg: 2, sugarG: 38 }),
  f("fruit-melon-cham", "참외(슬라이스)", "과일", 150, "1/4개", { calories: 34, carbsG: 8.5, proteinG: 0.8, fatG: 0.2, sodiumMg: 15, sugarG: 7.5 }),
  f("fruit-strawberry-kr", "논산딸기", "과일", 150, "10개", { calories: 32, carbsG: 7.7, proteinG: 0.7, fatG: 0.3, sodiumMg: 1, sugarG: 5 }),
  f("fruit-tangerine-deodeok", "노지귤", "과일", 100, "2개", { calories: 50, carbsG: 12, proteinG: 0.8, fatG: 0.3, sodiumMg: 2, sugarG: 10 }),
  f("fruit-grape-campbell", "캠벨포도", "과일", 150, "1송이", { calories: 70, carbsG: 18, proteinG: 0.7, fatG: 0.2, sodiumMg: 2, sugarG: 17 }),
  f("fruit-watermelon-yellow", "노란수박", "과일", 200, "1조각", { calories: 30, carbsG: 7.5, proteinG: 0.6, fatG: 0.2, sodiumMg: 1, sugarG: 6 }),
  f("fruit-apple-envy", "엔비사과", "과일", 180, "1개", { calories: 52, carbsG: 14, proteinG: 0.3, fatG: 0.2, sodiumMg: 1, sugarG: 10 }),
  f("veg-perilla-leaf", "깻잎", "채소", 5, "10장", { calories: 44, carbsG: 7, proteinG: 3.6, fatG: 0.8, sodiumMg: 3, fiberG: 6.5 }),
  f("veg-chwinamul", "취나물", "채소", 100, "1컵", { calories: 32, carbsG: 6, proteinG: 2.5, fatG: 0.4, sodiumMg: 15, fiberG: 3 }),
  f("veg-gosari", "고사리", "채소", 100, "1컵", { calories: 34, carbsG: 6.5, proteinG: 2, fatG: 0.3, sodiumMg: 8, fiberG: 4 }),
  f("veg-doraji", "도라지", "채소", 100, "1컵", { calories: 28, carbsG: 6, proteinG: 1.5, fatG: 0.2, sodiumMg: 12, fiberG: 2.5 }),
  f("veg-deodeok", "더덕", "채소", 100, "1컵", { calories: 38, carbsG: 8, proteinG: 1.8, fatG: 0.2, sodiumMg: 10, fiberG: 3 }),
  f("veg-shepherd-purse", "냉이", "채소", 100, "1컵", { calories: 27, carbsG: 4.5, proteinG: 2.3, fatG: 0.4, sodiumMg: 25, fiberG: 2 }),
  f("veg-ssuk", "쑥", "채소", 100, "1컵", { calories: 43, carbsG: 7, proteinG: 2.5, fatG: 0.5, sodiumMg: 20, fiberG: 3.5 }),
  f("veg-aster", "씀바귀", "채소", 100, "1컵", { calories: 30, carbsG: 5.5, proteinG: 2, fatG: 0.3, sodiumMg: 18, fiberG: 2.8 }),
  f("veg-burdock", "우엉", "채소", 100, "1컵", { calories: 72, carbsG: 17, proteinG: 1.5, fatG: 0.2, sodiumMg: 8, fiberG: 3.3 }),
  f("veg-lotus-root", "연근", "채소", 100, "1컵", { calories: 74, carbsG: 17, proteinG: 2.5, fatG: 0.1, sodiumMg: 40, fiberG: 4.9 }),
  f("veg-taro", "토란", "채소", 150, "1개", { calories: 112, carbsG: 26, proteinG: 1.5, fatG: 0.2, sodiumMg: 11, fiberG: 4.1 }),
  f("veg-water-dropwort", "미나리", "채소", 50, "1줌", { calories: 20, carbsG: 3.5, proteinG: 1.5, fatG: 0.2, sodiumMg: 15, fiberG: 2 }),
  f("veg-chicory", "치커리", "채소", 80, "1포기", { calories: 17, carbsG: 3.3, proteinG: 1.2, fatG: 0.2, sodiumMg: 22 }),
  f("veg-kkaennip", "깻잎(장아찌용)", "채소", 30, "1접시", { calories: 55, carbsG: 8, proteinG: 3, fatG: 1.5, sodiumMg: 450 }, ["깻잎장아찌"]),
  f("veg-mu-pickled", "무장아찌", "채소", 50, "1접시", { calories: 25, carbsG: 5.5, proteinG: 0.8, fatG: 0.1, sodiumMg: 500 }, ["무피클"]),
  f("veg-enoki", "팽이버섯", "채소", 100, "1봉", { calories: 37, carbsG: 7, proteinG: 2.7, fatG: 0.3, sodiumMg: 3 }),
  f("veg-shiitake-fresh", "표고버섯(생)", "채소", 100, "1컵", { calories: 34, carbsG: 7, proteinG: 2.2, fatG: 0.5, sodiumMg: 9, fiberG: 2.5 }),
  f("veg-wood-ear", "목이버섯(건)", "채소", 20, "1줌", { calories: 284, carbsG: 71, proteinG: 9, fatG: 0.7, sodiumMg: 15, fiberG: 45 }),
  f("veg-pumpkin-leaf", "호박잎", "채소", 100, "1컵", { calories: 19, carbsG: 3.4, proteinG: 1.5, fatG: 0.2, sodiumMg: 8, fiberG: 2 }),
  f("veg-sweet-potato-stem", "고구마순", "채소", 100, "1컵", { calories: 35, carbsG: 7, proteinG: 2, fatG: 0.3, sodiumMg: 12, fiberG: 2.5 }),
  f("veg-romaine-kr", "로메인", "채소", 80, "1포기", { calories: 17, carbsG: 3.3, proteinG: 1.2, fatG: 0.3, sodiumMg: 8 }),
  f("veg-chili-green", "풋고추", "채소", 15, "1개", { calories: 40, carbsG: 9, proteinG: 2, fatG: 0.4, sodiumMg: 3 }),
  f("veg-chili-red", "홍고추", "채소", 15, "1개", { calories: 31, carbsG: 7, proteinG: 1, fatG: 0.3, sodiumMg: 4 }),
  f("veg-crown-daisy", "쑥갓", "채소", 100, "1컵", { calories: 24, carbsG: 4, proteinG: 2.5, fatG: 0.4, sodiumMg: 118, fiberG: 2.5 }),
  f("veg-mustard-leaf", "갓", "채소", 100, "1컵", { calories: 27, carbsG: 4.7, proteinG: 2.6, fatG: 0.4, sodiumMg: 20, fiberG: 3.2 }),
  f("protein-jeyuk-bokkeum", "제육볶음", "단백", 150, "1인분", { calories: 195, carbsG: 6, proteinG: 16, fatG: 12, sodiumMg: 520 }, ["제육","돼지고기볶음"], "medium"),
  f("protein-dak-galbi", "닭갈비", "단백", 200, "1인분", { calories: 175, carbsG: 8, proteinG: 15, fatG: 9, sodiumMg: 480 }, ["닭갈비","춘천닭갈비"], "medium"),
  f("protein-buldak", "불닭", "단백", 150, "1인분", { calories: 210, carbsG: 5, proteinG: 18, fatG: 13, sodiumMg: 550 }, ["불닭볶음"], "low"),
  f("protein-samgyeopsal-grilled", "삼겹살(구이,양념)", "단백", 150, "1인분", { calories: 340, carbsG: 2, proteinG: 15, fatG: 30, sodiumMg: 380 }, ["양념삼겹","삼겹"], "low"),
  f("protein-moksal", "목살(구이)", "단백", 100, "1인분", { calories: 280, carbsG: 0, proteinG: 22, fatG: 21, sodiumMg: 65 }, ["목살","돼지목살"], "low"),
  f("protein-hangjeongsal", "항정살(구이)", "단백", 100, "1인분", { calories: 320, carbsG: 0, proteinG: 18, fatG: 27, sodiumMg: 70 }, ["항정살"], "low"),
  f("protein-dwaeji-galbi", "돼지갈비(구이)", "단백", 150, "1인분", { calories: 260, carbsG: 6, proteinG: 18, fatG: 18, sodiumMg: 420 }, ["LA갈비","양념갈비"], "medium"),
  f("protein-so-galbi", "소갈비(구이)", "단백", 150, "1인분", { calories: 290, carbsG: 5, proteinG: 20, fatG: 22, sodiumMg: 400 }, ["소갈비","갈비"], "medium"),
  f("protein-chadolbaegi", "차돌박이", "단백", 100, "1인분", { calories: 350, carbsG: 0, proteinG: 14, fatG: 32, sodiumMg: 55 }, ["차돌","소차돌"], "low"),
  f("protein-brisket-boil", "양지수육", "단백", 120, "1인분", { calories: 180, carbsG: 0, proteinG: 24, fatG: 9, sodiumMg: 80 }, ["수육","양지"], "low"),
  f("protein-tendon-beef", "사골고기", "단백", 100, "1인분", { calories: 200, carbsG: 0, proteinG: 22, fatG: 12, sodiumMg: 90 }, ["우족","꼬리"], "low"),
  f("protein-duck-roast", "오리구이", "단백", 150, "1인분", { calories: 240, carbsG: 0, proteinG: 22, fatG: 16, sodiumMg: 75 }, ["오리","훈제오리"], "low"),
  f("protein-duck-smoked", "훈제오리", "단백", 100, "1토막", { calories: 220, carbsG: 0, proteinG: 20, fatG: 15, sodiumMg: 650 }, ["훈제"], "low"),
  f("protein-lamb-skewer", "양꼬치", "단백", 80, "1꼬치", { calories: 250, carbsG: 2, proteinG: 20, fatG: 18, sodiumMg: 400 }, ["양고기"], "low"),
  f("protein-jeonbok", "전복구이", "단백", 80, "2마리", { calories: 105, carbsG: 8, proteinG: 14, fatG: 2, sodiumMg: 350 }, ["전복","전복구이"], "low"),
  f("protein-godeungeo-grilled", "고등어구이", "단백", 120, "1토막", { calories: 265, carbsG: 0, proteinG: 24, fatG: 18, sodiumMg: 95 }, ["고등어","구이고등어"], "low"),
  f("protein-godeungeo-jorim", "고등어조림", "단백", 150, "1토막", { calories: 180, carbsG: 8, proteinG: 18, fatG: 9, sodiumMg: 550 }, ["고등어조림"], "medium"),
  f("protein-galchi-jorim", "갈치조림", "단백", 150, "1토막", { calories: 165, carbsG: 7, proteinG: 17, fatG: 8, sodiumMg: 520 }, ["갈치","갈치조림"], "medium"),
  f("protein-galchi-grilled", "갈치구이", "단백", 120, "1토막", { calories: 195, carbsG: 0, proteinG: 20, fatG: 12, sodiumMg: 85 }, ["갈치구이"], "low"),
  f("protein-mackerel-blue", "삼치구이", "단백", 120, "1토막", { calories: 210, carbsG: 0, proteinG: 21, fatG: 13, sodiumMg: 90 }, ["삼치"], "low"),
  f("protein-croaker-yellow", "조기구이", "단백", 100, "1마리", { calories: 115, carbsG: 0, proteinG: 19, fatG: 4, sodiumMg: 80 }, ["조기","민어"], "low"),
  f("protein-flatfish", "광어회", "단백", 100, "1인분", { calories: 95, carbsG: 0, proteinG: 18, fatG: 2.5, sodiumMg: 60 }, ["광어","회"], "low"),
  f("protein-tuna-sashimi", "참치회", "단백", 100, "1인분", { calories: 130, carbsG: 0, proteinG: 28, fatG: 1.5, sodiumMg: 50 }, ["참치","참치회"], "low"),
  f("protein-salmon-sashimi", "연어회", "단백", 100, "1인분", { calories: 145, carbsG: 0, proteinG: 20, fatG: 7, sodiumMg: 55 }, ["연어회"], "low"),
  f("protein-octopus-boiled", "문어숙회", "단백", 100, "1인분", { calories: 82, carbsG: 2, proteinG: 16, fatG: 1, sodiumMg: 280 }, ["문어","문어숙회"], "low"),
  f("protein-jjukkumi-bokkeum", "쭈꾸미볶음", "단백", 150, "1인분", { calories: 120, carbsG: 6, proteinG: 14, fatG: 4.5, sodiumMg: 480 }, ["쭈꾸미","주꾸미"], "medium"),
  f("protein-nakji-bokkeum", "낙지볶음", "단백", 150, "1인분", { calories: 95, carbsG: 5, proteinG: 13, fatG: 2.5, sodiumMg: 450 }, ["낙지","낙지볶음"], "medium"),
  f("protein-ojingeo-bokkeum", "오징어볶음", "단백", 150, "1인분", { calories: 130, carbsG: 8, proteinG: 16, fatG: 4, sodiumMg: 420 }, ["오징어","오징어볶음"], "medium"),
  f("protein-ojingeo-sundae", "오징어순대", "단백", 120, "1인분", { calories: 155, carbsG: 10, proteinG: 14, fatG: 6, sodiumMg: 380 }, ["오징어순대"], "medium"),
  f("protein-anchovy-fried", "멸치볶음", "단백", 30, "1접시", { calories: 280, carbsG: 12, proteinG: 28, fatG: 14, sodiumMg: 520 }, ["멸치","볶음멸치"], "medium"),
  f("protein-anchovy-soup", "국물멸치", "단백", 10, "1줌", { calories: 200, carbsG: 0, proteinG: 42, fatG: 4, sodiumMg: 150 }, ["멸치국물용"], "low"),
  f("protein-jeotgal-shrimp", "새우젓", "단백", 15, "1큰술", { calories: 80, carbsG: 2, proteinG: 12, fatG: 2, sodiumMg: 2500 }, ["새우젓"], "low"),
  f("protein-jeotgal-anchovy", "멸치젓", "단백", 15, "1큰술", { calories: 95, carbsG: 3, proteinG: 14, fatG: 3, sodiumMg: 2800 }, ["멸치젓"], "low"),
  f("protein-jeotgal-kimchi", "젓갈", "단백", 30, "1접시", { calories: 65, carbsG: 4, proteinG: 8, fatG: 2, sodiumMg: 1800 }, ["젓","젓갈반찬"], "low"),
  f("protein-tofu-stew", "두부찌개", "단백", 200, "1인분", { calories: 75, carbsG: 4, proteinG: 6, fatG: 4.5, sodiumMg: 450 }, ["두부전골"], "low"),
  f("protein-tofu-pancake", "두부전", "단백", 80, "1장", { calories: 140, carbsG: 8, proteinG: 8, fatG: 8, sodiumMg: 280 }, ["두부부침"], "medium"),
  f("protein-egg-roll", "계란말이", "단백", 120, "1인분", { calories: 155, carbsG: 3, proteinG: 11, fatG: 11, sodiumMg: 320 }, ["계란말이","말이"], "low"),
  f("protein-egg-fried", "계란후라이", "단백", 50, "1개", { calories: 195, carbsG: 1, proteinG: 13, fatG: 15, sodiumMg: 140 }, ["후라이","프라이"], "low"),
  f("protein-egg-scramble", "계란볶음", "단백", 100, "1인분", { calories: 145, carbsG: 2, proteinG: 10, fatG: 11, sodiumMg: 250 }, ["계란볶음"], "low"),
  f("protein-boiled-pork-slice", "수육(돼지)", "단백", 100, "1인분", { calories: 220, carbsG: 0, proteinG: 20, fatG: 15, sodiumMg: 70 }, ["돼지수육","수육"], "low"),
  f("protein-liver-pork", "돼지간", "단백", 80, "1인분", { calories: 135, carbsG: 4, proteinG: 21, fatG: 4, sodiumMg: 80 }, ["간","돼지간"], "low"),
  f("protein-intestine-gopchang", "곱창(구이)", "단백", 100, "1인분", { calories: 230, carbsG: 0, proteinG: 18, fatG: 17, sodiumMg: 120 }, ["곱창","소곱창"], "low"),
  f("protein-intestine-daechang", "대창(구이)", "단백", 100, "1인분", { calories: 310, carbsG: 0, proteinG: 12, fatG: 28, sodiumMg: 95 }, ["대창"], "low"),
  f("protein-intestine-makchang", "막창(구이)", "단백", 100, "1인분", { calories: 280, carbsG: 0, proteinG: 15, fatG: 24, sodiumMg: 110 }, ["막창"], "low"),
  f("protein-blood-sausage", "순대", "단백", 150, "1인분", { calories: 155, carbsG: 18, proteinG: 8, fatG: 6, sodiumMg: 380 }, ["순대","순대국"], "medium"),
  f("protein-blood-sausage-soup", "순대국", "단백", 400, "1그릇", { calories: 55, carbsG: 6, proteinG: 4, fatG: 2, sodiumMg: 550 }, ["순댓국","국밥순대"], "medium"),
  f("protein-liver-soup", "선지해장국", "단백", 400, "1그릇", { calories: 50, carbsG: 4, proteinG: 5, fatG: 2, sodiumMg: 600 }, ["선지국","해장국"], "medium"),
  f("protein-pork-knuckle", "족발(삶은)", "단백", 150, "1인분", { calories: 230, carbsG: 0, proteinG: 22, fatG: 15, sodiumMg: 450 }, ["족발","보쌈족발"], "low"),
  f("protein-pork-feet", "족발(양념)", "단백", 150, "1인분", { calories: 250, carbsG: 5, proteinG: 20, fatG: 17, sodiumMg: 520 }, ["매운족발"], "medium"),
  f("protein-abalone-butter", "전복버터구이", "단백", 80, "2마리", { calories: 140, carbsG: 3, proteinG: 14, fatG: 8, sodiumMg: 320 }, ["버터전복"], "low"),
  f("protein-clam-steamed", "조개찜", "단백", 200, "1인분", { calories: 75, carbsG: 4, proteinG: 12, fatG: 1.5, sodiumMg: 420 }, ["조개","바지락"], "low"),
  f("protein-mussel-steamed", "홍합찜", "단백", 200, "1인분", { calories: 85, carbsG: 5, proteinG: 12, fatG: 2, sodiumMg: 380 }, ["홍합"], "low"),
  f("protein-crab-steamed", "꽃게찜", "단백", 200, "1인분", { calories: 95, carbsG: 2, proteinG: 18, fatG: 2, sodiumMg: 350 }, ["꽃게","대게"], "low"),
  f("protein-lobster", "랍스터(삶은)", "단백", 150, "1인분", { calories: 90, carbsG: 0, proteinG: 19, fatG: 1, sodiumMg: 380 }, ["랍스터"], "low"),
  f("protein-fish-cake-soup", "어묵탕", "단백", 300, "1그릇", { calories: 65, carbsG: 8, proteinG: 5, fatG: 2, sodiumMg: 550 }, ["오뎅탕","어묵국"], "medium"),
  f("protein-fish-cake-skewer", "어묵꼬치", "단백", 80, "1꼬치", { calories: 95, carbsG: 10, proteinG: 6, fatG: 3, sodiumMg: 650 }, ["오뎅","꼬치어묵"], "medium"),
  f("protein-twigim-assorted", "튀김모둠", "단백", 150, "1인분", { calories: 280, carbsG: 22, proteinG: 8, fatG: 17, sodiumMg: 420 }, ["튀김","모둠튀김"], "high"),
  f("protein-twigim-sweet-potato", "고구마튀김", "단백", 80, "2조각", { calories: 240, carbsG: 28, proteinG: 2, fatG: 13, sodiumMg: 180 }, ["고구마튀김"], "high"),
  f("protein-twigim-vegetable", "야채튀김", "단백", 100, "1인분", { calories: 220, carbsG: 20, proteinG: 4, fatG: 14, sodiumMg: 350 }, ["야채튀김"], "high"),
  f("protein-hotbar", "핫바", "단백", 70, "1개", { calories: 220, carbsG: 22, proteinG: 8, fatG: 11, sodiumMg: 550 }, ["핫바","어묵핫바"], "high"),
  f("protein-fish-sausage", "맛살", "단백", 30, "3줄", { calories: 95, carbsG: 10, proteinG: 8, fatG: 2, sodiumMg: 480 }, ["맛살","게맛살"], "medium"),
  f("protein-surimi-stick", "어묵바", "단백", 60, "1개", { calories: 180, carbsG: 18, proteinG: 7, fatG: 8, sodiumMg: 520 }, ["어묵바"], "high"),
  f("protein-dumpling-mandu-filling", "만두소", "단백", 100, "1컵", { calories: 180, carbsG: 8, proteinG: 12, fatG: 11, sodiumMg: 400 }, ["만두속"], "medium"),
  f("fat-perilla-oil", "들기름", "지방", 14, "1큰술", { calories: 884, carbsG: 0, proteinG: 0, fatG: 100, sodiumMg: 0 }, ["들기름"], "low"),
  f("fat-sesame-oil", "참기름", "지방", 14, "1큰술", { calories: 884, carbsG: 0, proteinG: 0, fatG: 100, sodiumMg: 0 }, ["참기름","기름"], "low"),
  f("fat-sesame-paste", "참깨페이스트", "지방", 15, "1큰술", { calories: 595, carbsG: 18, proteinG: 18, fatG: 52, sodiumMg: 20 }, ["참깨","흑임자"], "medium"),
  f("fat-gochujang-oil", "고추기름", "지방", 14, "1큰술", { calories: 884, carbsG: 0, proteinG: 0, fatG: 100, sodiumMg: 0 }, ["고추기름"], "low"),
  f("fat-pine-nut", "잣", "지방", 30, "1줌", { calories: 673, carbsG: 13, proteinG: 14, fatG: 68, sodiumMg: 2, fiberG: 3.7 }, ["잣"], "low"),
  f("fat-chestnut", "밤(생)", "지방", 50, "5알", { calories: 196, carbsG: 44, proteinG: 1.6, fatG: 1.2, sodiumMg: 2, fiberG: 3 }),
  f("fat-yulmu", "율무", "지방", 30, "1줌", { calories: 380, carbsG: 65, proteinG: 12, fatG: 8, sodiumMg: 5, fiberG: 15 }, ["율무차","율무"], "medium"),
  f("fat-black-sesame", "흑임자", "지방", 15, "1큰술", { calories: 573, carbsG: 24, proteinG: 18, fatG: 50, sodiumMg: 11, fiberG: 14 }, ["흑임자"], "medium"),
  f("fat-red-bean-paste", "팥앙금", "지방", 30, "1큰술", { calories: 250, carbsG: 48, proteinG: 6, fatG: 2, sodiumMg: 5, sugarG: 35 }, ["팥","앙금"], "high"),
  f("fat-gochujang", "고추장", "지방", 20, "1큰술", { calories: 140, carbsG: 28, proteinG: 3, fatG: 2, sodiumMg: 650 }, ["고추장","쌈장"], "medium"),
  f("banchan-kimchi-cub", "깍두기", "반찬", 50, "1접시", { calories: 18, carbsG: 3.5, proteinG: 0.8, fatG: 0.2, sodiumMg: 550, fiberG: 1.5 }, ["깍두기","무김치"], "low"),
  f("banchan-kimchi-chonggak", "총각김치", "반찬", 50, "1접시", { calories: 20, carbsG: 4, proteinG: 1, fatG: 0.3, sodiumMg: 580, fiberG: 2 }, ["총각","알타리"], "low"),
  f("banchan-kimchi-water", "물김치", "반찬", 200, "1그릇", { calories: 12, carbsG: 2, proteinG: 0.5, fatG: 0.1, sodiumMg: 400 }, ["동치미","물김치"], "low"),
  f("banchan-kimchi-dongchimi", "동치미", "반찬", 200, "1그릇", { calories: 10, carbsG: 2, proteinG: 0.4, fatG: 0, sodiumMg: 380 }, ["동치미","무국물"], "low"),
  f("banchan-kimchi-baek", "백김치", "반찬", 50, "1접시", { calories: 14, carbsG: 2.5, proteinG: 0.8, fatG: 0.2, sodiumMg: 420 }, ["백김치"], "low"),
  f("banchan-kimchi-oi", "오이소박이", "반찬", 50, "1접시", { calories: 16, carbsG: 3, proteinG: 0.6, fatG: 0.2, sodiumMg: 500 }, ["오이김치","소박이"], "low"),
  f("banchan-kimchi-kkakdugi", "깍두기(매운)", "반찬", 50, "1접시", { calories: 19, carbsG: 3.8, proteinG: 0.8, fatG: 0.3, sodiumMg: 560 }, ["매운깍두기"], "low"),
  f("banchan-kimchi-bossam", "보쌈김치", "반찬", 80, "1접시", { calories: 22, carbsG: 4, proteinG: 1.2, fatG: 0.4, sodiumMg: 520 }, ["보쌈김치"], "low"),
  f("banchan-myeolchi-bokkeum", "멸치볶음반찬", "반찬", 30, "1접시", { calories: 280, carbsG: 12, proteinG: 28, fatG: 14, sodiumMg: 520 }, ["멸치볶음"], "medium"),
  f("banchan-jangjorim", "장조림", "반찬", 50, "1접시", { calories: 180, carbsG: 8, proteinG: 14, fatG: 10, sodiumMg: 650 }, ["장조림","소고기장조림"], "medium"),
  f("banchan-jangajji", "장아찌", "반찬", 40, "1접시", { calories: 35, carbsG: 7, proteinG: 1, fatG: 0.3, sodiumMg: 900 }, ["장아찌","무장아찌"], "low"),
  f("banchan-mu-salad", "무생채", "반찬", 80, "1접시", { calories: 32, carbsG: 7, proteinG: 0.8, fatG: 0.2, sodiumMg: 350 }, ["무생채","생채"], "low"),
  f("banchan-kongjaban", "콩자반", "반찬", 40, "1접시", { calories: 120, carbsG: 8, proteinG: 10, fatG: 5, sodiumMg: 400 }, ["검은콩","콩자반"], "medium"),
  f("banchan-kongnamul-muchim", "콩나물무침", "반찬", 80, "1접시", { calories: 40, carbsG: 5, proteinG: 3, fatG: 1.5, sodiumMg: 280 }, ["콩나물","나물"], "low"),
  f("banchan-sigeumchi-namul", "시금치나물", "반찬", 80, "1접시", { calories: 35, carbsG: 4, proteinG: 2.5, fatG: 1.5, sodiumMg: 300 }, ["시금치","나물"], "low"),
  f("banchan-miyeok-muchim", "미역무침", "반찬", 80, "1접시", { calories: 55, carbsG: 6, proteinG: 2.5, fatG: 2.5, sodiumMg: 450 }, ["미역나물","미역"], "low"),
  f("banchan-gosari-namul", "고사리나물", "반찬", 80, "1접시", { calories: 45, carbsG: 7, proteinG: 2.5, fatG: 1.5, sodiumMg: 320 }, ["고사리","나물"], "low"),
  f("banchan-doraji-muchim", "도라지무침", "반찬", 80, "1접시", { calories: 42, carbsG: 7, proteinG: 1.8, fatG: 1.2, sodiumMg: 310 }, ["도라지"], "low"),
  f("banchan-mu-namul", "무나물", "반찬", 80, "1접시", { calories: 28, carbsG: 5.5, proteinG: 0.8, fatG: 0.5, sodiumMg: 290 }, ["무나물"], "low"),
  f("banchan-gosari-deodeok", "더덕무침", "반찬", 80, "1접시", { calories: 48, carbsG: 8, proteinG: 2, fatG: 1.5, sodiumMg: 300 }, ["더덕"], "low"),
  f("banchan-oi-muchim", "오이무침", "반찬", 80, "1접시", { calories: 25, carbsG: 4, proteinG: 0.8, fatG: 0.8, sodiumMg: 280 }, ["오이무침","오이"], "low"),
  f("banchan-kongnamul-guk", "콩나물국", "반찬", 300, "1그릇", { calories: 25, carbsG: 3, proteinG: 2, fatG: 0.8, sodiumMg: 450 }, ["콩나물국밥","국"], "low"),
  f("banchan-miso-guk", "미소국", "반찬", 300, "1그릇", { calories: 30, carbsG: 3, proteinG: 2.5, fatG: 1.2, sodiumMg: 500 }, ["미소","된장국"], "low"),
  f("banchan-cheonggukjang", "청국장", "반찬", 300, "1그릇", { calories: 50, carbsG: 4, proteinG: 4.5, fatG: 2, sodiumMg: 420 }, ["청국장찌개","청국"], "low"),
  f("banchan-sundubu-jjigae", "순두부찌개", "반찬", 350, "1그릇", { calories: 55, carbsG: 3, proteinG: 4.5, fatG: 3.5, sodiumMg: 550 }, ["순두부","두부찌개"], "low"),
  f("banchan-budae-jjigae", "부대찌개", "반찬", 400, "1그릇", { calories: 75, carbsG: 6, proteinG: 5, fatG: 4, sodiumMg: 750 }, ["부대찌개","부대"], "medium"),
  f("banchan-kimchi-jjigae-ext", "김치찌개(얼큰)", "반찬", 350, "1그릇", { calories: 58, carbsG: 5, proteinG: 4.5, fatG: 2.8, sodiumMg: 920 }, ["김치찌개","찌개"], "low"),
  f("banchan-doenjang-jjigae", "된장찌개", "반찬", 350, "1그릇", { calories: 48, carbsG: 4, proteinG: 3.5, fatG: 2.2, sodiumMg: 820 }, ["된장찌개","찌개"], "low"),
  f("banchan-kongbiji-jjigae", "콩비지찌개", "반찬", 350, "1그릇", { calories: 52, carbsG: 4, proteinG: 4, fatG: 2.5, sodiumMg: 480 }, ["콩비지","비지찌개"], "low"),
  f("banchan-seolleongtang", "설렁탕", "반찬", 500, "1그릇", { calories: 45, carbsG: 2, proteinG: 4.5, fatG: 2.5, sodiumMg: 380 }, ["설렁탕","곰탕"], "low"),
  f("banchan-galbitang", "갈비탕", "반찬", 500, "1그릇", { calories: 55, carbsG: 3, proteinG: 5, fatG: 2.8, sodiumMg: 420 }, ["갈비탕","탕"], "low"),
  f("banchan-gamjatang", "감자탕", "반찬", 500, "1그릇", { calories: 65, carbsG: 5, proteinG: 5.5, fatG: 3, sodiumMg: 550 }, ["감자탕","뼈해장국"], "medium"),
  f("banchan-samgyetang", "삼계탕", "반찬", 800, "1그릇", { calories: 55, carbsG: 2, proteinG: 5.5, fatG: 2.8, sodiumMg: 350 }, ["삼계탕","삼계"], "low"),
  f("banchan-yukgaejang", "육개장", "반찬", 400, "1그릇", { calories: 50, carbsG: 3, proteinG: 5, fatG: 2.5, sodiumMg: 580 }, ["육개장","해장국"], "low"),
  f("banchan-dak-bokkeum-tang", "닭볶음탕", "반찬", 500, "1그릇", { calories: 70, carbsG: 5, proteinG: 6, fatG: 3.5, sodiumMg: 520 }, ["닭볶음탕","닭도리탕"], "medium"),
  f("banchan-maeuntang", "매운탕", "반찬", 400, "1그릇", { calories: 60, carbsG: 4, proteinG: 6, fatG: 2.5, sodiumMg: 600 }, ["매운탕","해물탕"], "low"),
  f("banchan-altang", "알탕", "반찬", 400, "1그릇", { calories: 55, carbsG: 3, proteinG: 6, fatG: 2.5, sodiumMg: 550 }, ["알탕","명란"], "low"),
  f("banchan-sagol-guk", "사골국", "반찬", 300, "1그릇", { calories: 35, carbsG: 1, proteinG: 3, fatG: 2, sodiumMg: 350 }, ["사골","곰국"], "low"),
  f("banchan-gukbap", "국밥(돼지)", "반찬", 500, "1그릇", { calories: 75, carbsG: 8, proteinG: 5, fatG: 3, sodiumMg: 480 }, ["국밥","돼지국밥"], "medium"),
  f("banchan-sundaeguk", "순대국밥", "반찬", 500, "1그릇", { calories: 65, carbsG: 9, proteinG: 4.5, fatG: 2, sodiumMg: 520 }, ["순대국","국밥"], "medium"),
  f("banchan-chueotang", "추어탕", "반찬", 400, "1그릇", { calories: 48, carbsG: 3, proteinG: 5, fatG: 2, sodiumMg: 400 }, ["추어탕","미꾸라지"], "low"),
  f("banchan-chicken-soup", "닭개장", "반찬", 400, "1그릇", { calories: 42, carbsG: 2, proteinG: 4.5, fatG: 2, sodiumMg: 380 }, ["닭개장"], "low"),
  f("banchan-ojingeo-soup", "오징어국", "반찬", 300, "1그릇", { calories: 38, carbsG: 3, proteinG: 4, fatG: 1.5, sodiumMg: 450 }, ["오징어국"], "low"),
  f("banchan-doenjang-guk", "된장국", "반찬", 300, "1그릇", { calories: 32, carbsG: 3, proteinG: 2.5, fatG: 1.5, sodiumMg: 480 }, ["된장국"], "low"),
  f("banchan-tteokguk-broth", "떡국(국물)", "반찬", 400, "1그릇", { calories: 55, carbsG: 8, proteinG: 2.5, fatG: 1.5, sodiumMg: 500 }, ["떡국"], "medium"),
  f("banchan-manduguk-broth", "만두국(국물)", "반찬", 400, "1그릇", { calories: 60, carbsG: 7, proteinG: 3.5, fatG: 2, sodiumMg: 520 }, ["만두국"], "medium"),
  f("banchan-jogaetang", "조개탕", "반찬", 400, "1그릇", { calories: 45, carbsG: 3, proteinG: 5, fatG: 1.5, sodiumMg: 480 }, ["조개탕","바지락칼국수"], "low"),
  f("banchan-haemultang", "해물탕", "반찬", 500, "1그릇", { calories: 58, carbsG: 4, proteinG: 6, fatG: 2.5, sodiumMg: 620 }, ["해물탕","탕"], "low"),
  f("banchan-ujuk-tang", "우족탕", "반찬", 500, "1그릇", { calories: 50, carbsG: 2, proteinG: 5, fatG: 2.8, sodiumMg: 400 }, ["우족","꼬리탕"], "low"),
  f("banchan-gyeranjjim-ext", "계란찜(반찬)", "반찬", 150, "1인분", { calories: 120, carbsG: 2, proteinG: 10, fatG: 8, sodiumMg: 200 }, ["계란찜","찜"], "low"),
  f("banchan-myulchi-jjim", "멸치찜", "반찬", 80, "1접시", { calories: 180, carbsG: 10, proteinG: 22, fatG: 7, sodiumMg: 480 }, ["멸치찜"], "medium"),
  f("banchan-tofu-jorim", "두부조림", "반찬", 120, "1인분", { calories: 95, carbsG: 5, proteinG: 7, fatG: 5.5, sodiumMg: 420 }, ["두부조림"], "low"),
  f("banchan-oden-broth", "어묵국물", "반찬", 300, "1그릇", { calories: 25, carbsG: 3, proteinG: 2, fatG: 0.8, sodiumMg: 600 }, ["오뎅국물","어묵탕"], "medium"),
  f("meal-dolsot-bibimbap", "돌솥비빔밥", "식사", 450, "1그릇", { calories: 145, carbsG: 20, proteinG: 6, fatG: 5, sodiumMg: 380 }, ["돌솥","비빔밥"], "high"),
  f("meal-yeolmu-bibimbap", "열무비빔밥", "식사", 400, "1그릇", { calories: 125, carbsG: 18, proteinG: 5, fatG: 3.5, sodiumMg: 350 }, ["열무비빔"], "high"),
  f("meal-hoedeopbap", "회덮밥", "식사", 400, "1그릇", { calories: 130, carbsG: 18, proteinG: 8, fatG: 3, sodiumMg: 320 }, ["회덮밥","연어덮밥"], "high"),
  f("meal-oyakodon-kr", "오야코동", "식사", 400, "1그릇", { calories: 155, carbsG: 20, proteinG: 8, fatG: 5, sodiumMg: 400 }, ["오야코","덮밥"], "high"),
  f("meal-jeyuk-deopbap", "제육덮밥", "식사", 400, "1그릇", { calories: 175, carbsG: 22, proteinG: 9, fatG: 6, sodiumMg: 450 }, ["제육","제육덮밥"], "high"),
  f("meal-bulgogi-deopbap", "불고기덮밥", "식사", 400, "1그릇", { calories: 170, carbsG: 22, proteinG: 9, fatG: 5.5, sodiumMg: 420 }, ["불고기덮밥"], "high"),
  f("meal-dakgalbi-deopbap", "닭갈비덮밥", "식사", 400, "1그릇", { calories: 165, carbsG: 21, proteinG: 9, fatG: 5, sodiumMg: 430 }, ["닭갈비덮밥"], "high"),
  f("meal-kimchi-deopbap", "김치덮밥", "식사", 400, "1그릇", { calories: 150, carbsG: 22, proteinG: 6, fatG: 4.5, sodiumMg: 480 }, ["김치덮밥"], "high"),
  f("meal-nakji-deopbap", "낙지덮밥", "식사", 400, "1그릇", { calories: 140, carbsG: 20, proteinG: 8, fatG: 3.5, sodiumMg: 400 }, ["낙지덮밥"], "high"),
  f("meal-oe-deopbap", "오징어덮밥", "식사", 400, "1그릇", { calories: 145, carbsG: 21, proteinG: 8, fatG: 3.5, sodiumMg: 410 }, ["오징어덮밥"], "high"),
  f("meal-samgyeopsal-deopbap", "삼겹덮밥", "식사", 400, "1그릇", { calories: 195, carbsG: 20, proteinG: 8, fatG: 9, sodiumMg: 400 }, ["삼겹덮밥"], "high"),
  f("meal-teriyaki-deopbap", "데리야끼덮밥", "식사", 400, "1그릇", { calories: 160, carbsG: 24, proteinG: 8, fatG: 4, sodiumMg: 450 }, ["데리야끼"], "high"),
  f("meal-curry-deopbap", "카레덮밥", "식사", 400, "1그릇", { calories: 155, carbsG: 23, proteinG: 5, fatG: 5, sodiumMg: 480 }, ["카레덮밥"], "high"),
  f("meal-omurice", "오므라이스", "식사", 400, "1그릇", { calories: 165, carbsG: 20, proteinG: 7, fatG: 6, sodiumMg: 420 }, ["오므라이스","오믈렛"], "high"),
  f("meal-kimchi-bokkeumbap", "김치볶음밥(식사)", "식사", 350, "1그릇", { calories: 155, carbsG: 22, proteinG: 5, fatG: 5, sodiumMg: 450 }, ["볶음밥"], "high"),
  f("meal-nakji-bokkeumbap", "낙지볶음밥", "식사", 350, "1그릇", { calories: 150, carbsG: 21, proteinG: 7, fatG: 4, sodiumMg: 420 }, ["낙지볶음밥"], "high"),
  f("meal-gimbap-tuna-mayo", "참치마요김밥", "식사", 250, "1줄", { calories: 160, carbsG: 23, proteinG: 6, fatG: 5.5, sodiumMg: 330 }, ["참치김밥","참치마요"], "high"),
  f("meal-gimbap-chamchi", "참치김밥", "식사", 250, "1줄", { calories: 155, carbsG: 22, proteinG: 6, fatG: 5, sodiumMg: 320 }, ["참치"], "high"),
  f("meal-gimbap-cheese", "치즈김밥", "식사", 250, "1줄", { calories: 175, carbsG: 22, proteinG: 7, fatG: 7, sodiumMg: 380 }, ["치즈김밥"], "high"),
  f("meal-gimbap-egg", "계란김밥", "식사", 250, "1줄", { calories: 150, carbsG: 22, proteinG: 6, fatG: 4.5, sodiumMg: 300 }, ["계란김밥"], "high"),
  f("meal-gimbap-donkkaseu", "돈까스김밥", "식사", 280, "1줄", { calories: 195, carbsG: 24, proteinG: 7, fatG: 8, sodiumMg: 400 }, ["돈까스김밥"], "high"),
  f("meal-gimbap-samgyeopsal", "삼겹김밥", "식사", 280, "1줄", { calories: 210, carbsG: 22, proteinG: 8, fatG: 10, sodiumMg: 380 }, ["삼겹김밥"], "high"),
  f("meal-gimbap-yachae", "야채김밥", "식사", 220, "1줄", { calories: 130, carbsG: 24, proteinG: 3.5, fatG: 2.5, sodiumMg: 280 }, ["야채김밥","채소김밥"], "high"),
  f("meal-gimbap-kimchi", "김치김밥", "식사", 250, "1줄", { calories: 145, carbsG: 23, proteinG: 4.5, fatG: 3.5, sodiumMg: 400 }, ["김치김밥"], "high"),
  f("meal-gimbap-nude", "추억의누드김밥", "식사", 200, "1줄", { calories: 125, carbsG: 24, proteinG: 3, fatG: 1.5, sodiumMg: 250 }, ["누드김밥"], "high"),
  f("meal-gimbap-chungmu", "충무김밥", "식사", 200, "1줄", { calories: 135, carbsG: 26, proteinG: 3.5, fatG: 1.8, sodiumMg: 320 }, ["충무","충무김밥"], "high"),
  f("meal-gimbap-wrapped", "속초꼬막김밥", "식사", 250, "1줄", { calories: 150, carbsG: 22, proteinG: 7, fatG: 4, sodiumMg: 350 }, ["꼬막김밥"], "high"),
  f("meal-triangle-tuna", "삼각김밥(참치)", "식사", 110, "1개", { calories: 168, carbsG: 30, proteinG: 5, fatG: 3.5, sodiumMg: 360 }, ["참치삼각","삼각"], "high"),
  f("meal-triangle-spam", "삼각김밥(스팸)", "식사", 110, "1개", { calories: 175, carbsG: 29, proteinG: 5.5, fatG: 4.5, sodiumMg: 400 }, ["스팸삼각"], "high"),
  f("meal-triangle-kimchi", "삼각김밥(김치)", "식사", 110, "1개", { calories: 160, carbsG: 30, proteinG: 4, fatG: 3, sodiumMg: 380 }, ["김치삼각"], "high"),
  f("meal-triangle-mayo", "삼각김밥(마요)", "식사", 110, "1개", { calories: 170, carbsG: 29, proteinG: 4.5, fatG: 4, sodiumMg: 370 }, ["마요삼각"], "high"),
  f("meal-triangle-bulgogi", "삼각김밥(불고기)", "식사", 110, "1개", { calories: 172, carbsG: 29, proteinG: 5.5, fatG: 4, sodiumMg: 390 }, ["불고기삼각"], "high"),
  f("meal-triangle-shrimp", "삼각김밥(새우)", "식사", 110, "1개", { calories: 165, carbsG: 28, proteinG: 5, fatG: 3.5, sodiumMg: 360 }, ["새우삼각"], "high"),
  f("meal-triangle-vegetable", "삼각김밥(야채)", "식사", 110, "1개", { calories: 155, carbsG: 30, proteinG: 3.5, fatG: 2.5, sodiumMg: 340 }, ["야채삼각"], "high"),
  f("meal-lunchbox-spam", "스팸도시락", "식사", 450, "1개", { calories: 155, carbsG: 20, proteinG: 7, fatG: 5.5, sodiumMg: 450 }, ["스팸","도시락"], "high"),
  f("meal-lunchbox-chicken", "치킨도시락", "식사", 450, "1개", { calories: 165, carbsG: 21, proteinG: 8, fatG: 6, sodiumMg: 420 }, ["치킨도시락"], "high"),
  f("meal-lunchbox-bulgogi", "불고기도시락", "식사", 450, "1개", { calories: 160, carbsG: 20, proteinG: 8, fatG: 5.5, sodiumMg: 430 }, ["불고기도시락"], "high"),
  f("meal-lunchbox-jeon", "제육도시락", "식사", 450, "1개", { calories: 170, carbsG: 21, proteinG: 8, fatG: 6.5, sodiumMg: 460 }, ["제육도시락"], "high"),
  f("meal-lunchbox-fried-rice", "볶음밥도시락", "식사", 450, "1개", { calories: 175, carbsG: 24, proteinG: 6, fatG: 6, sodiumMg: 440 }, ["볶음밥"], "high"),
  f("meal-tteokbokki-ext", "즉석떡볶이", "식사", 300, "1인분", { calories: 150, carbsG: 31, proteinG: 3, fatG: 2.5, sodiumMg: 620 }, ["떡볶이","분식"], "high"),
  f("meal-tteokbokki-rose", "로제떡볶이", "식사", 300, "1인분", { calories: 165, carbsG: 28, proteinG: 4, fatG: 5, sodiumMg: 580 }, ["로제떡볶이"], "high"),
  f("meal-tteokbokki-mala", "마라떡볶이", "식사", 300, "1인분", { calories: 155, carbsG: 29, proteinG: 3.5, fatG: 4, sodiumMg: 650 }, ["마라떡볶이"], "high"),
  f("meal-sundae-bokkeum", "순대볶음", "식사", 250, "1인분", { calories: 165, carbsG: 20, proteinG: 8, fatG: 6, sodiumMg: 480 }, ["순대볶음","분식"], "medium"),
  f("meal-sundae-twigim", "순대튀김", "식사", 150, "1인분", { calories: 220, carbsG: 22, proteinG: 9, fatG: 11, sodiumMg: 420 }, ["순대튀김"], "high"),
  f("meal-fish-cake-plate", "어묵접시", "식사", 200, "1인분", { calories: 95, carbsG: 10, proteinG: 6, fatG: 3, sodiumMg: 650 }, ["어묵","분식"], "medium"),
  f("meal-donkkaseu-curry", "카레돈까스", "식사", 450, "1인분", { calories: 175, carbsG: 22, proteinG: 10, fatG: 7, sodiumMg: 480 }, ["카레까스","돈까스"], "high"),
  f("meal-donkkaseu-cheese", "치즈돈까스", "식사", 400, "1인분", { calories: 270, carbsG: 22, proteinG: 14, fatG: 15, sodiumMg: 500 }, ["치즈까스"], "high"),
  f("meal-donkkaseu-fish", "생선까스", "식사", 350, "1인분", { calories: 240, carbsG: 20, proteinG: 14, fatG: 12, sodiumMg: 450 }, ["생선까스"], "high"),
  f("meal-katsudon", "가츠동", "식사", 450, "1그릇", { calories: 170, carbsG: 22, proteinG: 10, fatG: 6, sodiumMg: 460 }, ["가츠동","돈까스덮밥"], "high"),
  f("meal-pork-cutlet-set", "돈까스정식", "식사", 500, "1인분", { calories: 200, carbsG: 22, proteinG: 12, fatG: 9, sodiumMg: 480 }, ["정식","돈까스"], "high"),
  f("meal-tangsuyuk", "탕수육", "식사", 300, "1인분", { calories: 230, carbsG: 22, proteinG: 12, fatG: 11, sodiumMg: 520 }, ["탕수육","중식"], "high"),
  f("meal-kkanpunggi", "깐풍기", "식사", 250, "1인분", { calories: 245, carbsG: 12, proteinG: 18, fatG: 14, sodiumMg: 550 }, ["깐풍기","중식"], "medium"),
  f("meal-yuringi", "유린기", "식사", 250, "1인분", { calories: 220, carbsG: 10, proteinG: 20, fatG: 12, sodiumMg: 480 }, ["유린기"], "medium"),
  f("meal-mapadubu", "마파두부", "식사", 300, "1인분", { calories: 120, carbsG: 6, proteinG: 8, fatG: 7, sodiumMg: 600 }, ["마파두부","중식"], "medium"),
  f("meal-ganjjajang", "간짜장", "식사", 400, "1그릇", { calories: 140, carbsG: 21, proteinG: 5, fatG: 4.5, sodiumMg: 580 }, ["간짜장","짜장"], "high"),
  f("meal-uljjang-jjajang", "울짜장", "식사", 450, "1그릇", { calories: 135, carbsG: 20, proteinG: 5, fatG: 4, sodiumMg: 560 }, ["울짜장"], "high"),
  f("meal-gomtang-noodle", "곰탕면", "식사", 400, "1그릇", { calories: 95, carbsG: 16, proteinG: 5, fatG: 2, sodiumMg: 480 }, ["곰탕"], "high"),
  f("meal-naengmyeon-dongchimi", "동치미냉면", "식사", 400, "1그릇", { calories: 90, carbsG: 19, proteinG: 4, fatG: 0.6, sodiumMg: 500 }, ["동치미냉면"], "high"),
  f("meal-mulhoe", "물회", "식사", 400, "1그릇", { calories: 75, carbsG: 8, proteinG: 8, fatG: 1.5, sodiumMg: 450 }, ["물회","회"], "medium"),
  f("meal-bossam-set", "보쌈정식", "식사", 400, "1인분", { calories: 200, carbsG: 5, proteinG: 16, fatG: 14, sodiumMg: 350 }, ["보쌈","정식"], "medium"),
  f("meal-jokbal-set", "족발정식", "식사", 400, "1인분", { calories: 210, carbsG: 3, proteinG: 18, fatG: 14, sodiumMg: 480 }, ["족발","정식"], "low"),
  f("meal-samgyetang-set", "삼계탕정식", "식사", 800, "1인분", { calories: 60, carbsG: 2, proteinG: 6, fatG: 3, sodiumMg: 360 }, ["삼계","정식"], "low"),
  f("meal-pyeonsu", "편수", "식사", 80, "1개", { calories: 180, carbsG: 32, proteinG: 5, fatG: 3, sodiumMg: 280 }, ["편수","만두"], "high"),
  f("meal-mandu-gun", "군만두(분식)", "식사", 150, "5개", { calories: 220, carbsG: 28, proteinG: 8, fatG: 8, sodiumMg: 450 }, ["군만두"], "high"),
  f("meal-sungeo-gui", "숭어구이", "식사", 200, "1마리", { calories: 140, carbsG: 0, proteinG: 20, fatG: 6, sodiumMg: 90 }, ["숭어"], "low"),
  f("meal-hoe-deungshim", "회덧심", "식사", 150, "1인분", { calories: 125, carbsG: 0, proteinG: 24, fatG: 3, sodiumMg: 55 }, ["모둠회","회"], "low"),
  f("meal-chobap-set", "초밥세트", "식사", 250, "10피스", { calories: 155, carbsG: 28, proteinG: 6, fatG: 2.5, sodiumMg: 420 }, ["초밥","스시"], "high"),
  f("meal-kimbap-chicken", "치킨마요김밥", "식사", 250, "1줄", { calories: 165, carbsG: 22, proteinG: 7, fatG: 6, sodiumMg: 350 }, ["치킨김밥"], "high"),
  f("meal-kimbap-spam", "스팸김밥", "식사", 260, "1줄", { calories: 185, carbsG: 22, proteinG: 7, fatG: 8, sodiumMg: 450 }, ["스팸김밥"], "high"),
  f("meal-kimbap-mayo", "마요김밥", "식사", 250, "1줄", { calories: 170, carbsG: 23, proteinG: 5, fatG: 6.5, sodiumMg: 340 }, ["마요김밥"], "high"),
  f("meal-kimbap-anchovy", "멸치김밥", "식사", 240, "1줄", { calories: 145, carbsG: 24, proteinG: 6, fatG: 3.5, sodiumMg: 380 }, ["멸치김밥"], "high"),
  f("meal-kimbap-triangle-fried", "주먹밥(튀김)", "식사", 120, "1개", { calories: 200, carbsG: 28, proteinG: 5, fatG: 7, sodiumMg: 380 }, ["주먹밥"], "high"),
  f("meal-bibim-myeon", "비빔면", "식사", 350, "1그릇", { calories: 125, carbsG: 24, proteinG: 4, fatG: 2, sodiumMg: 450 }, ["비빔면","라면"], "high"),
  f("meal-ramyeon-budae", "부대라면", "식사", 550, "1봉", { calories: 95, carbsG: 12, proteinG: 4, fatG: 4, sodiumMg: 700 }, ["부대라면"], "high"),
  f("meal-ramyeon-kimchi", "김치라면", "식사", 500, "1봉", { calories: 90, carbsG: 13, proteinG: 2.5, fatG: 3.5, sodiumMg: 680 }, ["김치라면"], "high"),
  f("meal-ramyeon-sari", "사리", "식사", 100, "1인분", { calories: 140, carbsG: 32, proteinG: 2.5, fatG: 0.3, sodiumMg: 10 }, ["라면사리","당면사리"], "high"),
  f("meal-pajeon", "파전", "식사", 200, "1/4판", { calories: 195, carbsG: 22, proteinG: 5, fatG: 9, sodiumMg: 420 }, ["파전","전"], "high"),
  f("meal-kimchi-jeon", "김치전", "식사", 200, "1/4판", { calories: 185, carbsG: 20, proteinG: 5, fatG: 8.5, sodiumMg: 450 }, ["김치전"], "high"),
  f("meal-haemul-jeon", "해물파전", "식사", 250, "1/4판", { calories: 200, carbsG: 21, proteinG: 8, fatG: 9, sodiumMg: 480 }, ["해물파전","해물전"], "high"),
  f("meal-bindaetteok", "빈대떡", "식사", 150, "1장", { calories: 210, carbsG: 28, proteinG: 6, fatG: 8, sodiumMg: 380 }, ["빈대떡","녹두전"], "high"),
  f("meal-gamjajeon", "감자전", "식사", 150, "1장", { calories: 175, carbsG: 24, proteinG: 3, fatG: 7, sodiumMg: 320 }, ["감자전"], "high"),
  f("meal-tofu-jeon", "두부전", "식사", 120, "2장", { calories: 140, carbsG: 8, proteinG: 8, fatG: 8, sodiumMg: 280 }, ["두부전"], "medium"),
  f("meal-sujeonggwa", "수정과(식사용)", "식사", 200, "1그릇", { calories: 55, carbsG: 14, proteinG: 0.2, fatG: 0, sodiumMg: 5, sugarG: 12 }, ["수정과"], "high"),
  f("snack-honey-bread", "허니브레드", "간식", 150, "1인분", { calories: 350, carbsG: 48, proteinG: 5, fatG: 16, sodiumMg: 280, sugarG: 28 }, ["허니브레드"], "high"),
  f("snack-sinkbread", "싱크브레드", "간식", 120, "1조각", { calories: 320, carbsG: 42, proteinG: 5, fatG: 14, sodiumMg: 250, sugarG: 22 }, ["싱크브레드"], "high"),
  f("snack-bingsu-mango", "망고빙수", "간식", 400, "1그릇", { calories: 110, carbsG: 24, proteinG: 2, fatG: 1.5, sodiumMg: 60, sugarG: 20 }, ["망고빙수","빙수"], "high"),
  f("snack-bingsu-injeolmi", "인절미빙수", "간식", 400, "1그릇", { calories: 125, carbsG: 26, proteinG: 3, fatG: 2.5, sodiumMg: 70, sugarG: 18 }, ["인절미빙수"], "high"),
  f("snack-bingsu-strawberry", "딸기빙수", "간식", 400, "1그릇", { calories: 105, carbsG: 23, proteinG: 2, fatG: 1.2, sodiumMg: 55, sugarG: 19 }, ["딸기빙수"], "high"),
  f("snack-waffle-kr", "크로플", "간식", 120, "1개", { calories: 320, carbsG: 40, proteinG: 5, fatG: 16, sodiumMg: 200, sugarG: 18 }, ["크로플","크로와플"], "high"),
  f("snack-corn-dog", "핫도그(치즈)", "간식", 120, "1개", { calories: 280, carbsG: 32, proteinG: 8, fatG: 14, sodiumMg: 550 }, ["핫도그","치즈핫도그"], "high"),
  f("snack-corn-dog-plain", "핫도그(일반)", "간식", 100, "1개", { calories: 250, carbsG: 30, proteinG: 7, fatG: 12, sodiumMg: 520 }, ["핫도그"], "high"),
  f("snack-tornado-potato", "회오리감자", "간식", 150, "1개", { calories: 290, carbsG: 35, proteinG: 4, fatG: 15, sodiumMg: 400 }, ["회오리감자"], "high"),
  f("snack-fish-cake-cup", "어묵컵", "간식", 150, "1컵", { calories: 70, carbsG: 9, proteinG: 5, fatG: 2, sodiumMg: 600 }, ["어묵컵"], "medium"),
  f("snack-dalgona", "달고나", "간식", 20, "1개", { calories: 390, carbsG: 95, proteinG: 0, fatG: 0, sodiumMg: 5, sugarG: 90 }, ["달고나","뽑기"], "high"),
  f("snack-chocopie", "초코파이", "간식", 30, "1개", { calories: 420, carbsG: 58, proteinG: 4, fatG: 19, sodiumMg: 180, sugarG: 35 }, ["초코파이","오리온"], "high"),
  f("snack-chocopie-green", "초코파이(그린)", "간식", 30, "1개", { calories: 410, carbsG: 56, proteinG: 4, fatG: 18, sodiumMg: 170, sugarG: 32 }, ["그린티초코파이"], "high"),
  f("snack-monster", "몬스터에너지", "간식", 30, "1개", { calories: 380, carbsG: 55, proteinG: 4, fatG: 14, sodiumMg: 200, sugarG: 30 }, ["몬스터","과자"], "high"),
  f("snack-honey-butter-chip", "허니버터칩", "간식", 30, "1봉", { calories: 530, carbsG: 55, proteinG: 6, fatG: 32, sodiumMg: 450 }, ["허니버터칩","감자칩"], "high"),
  f("snack-swing-chip", "스윙칩", "간식", 30, "1봉", { calories: 520, carbsG: 54, proteinG: 6, fatG: 31, sodiumMg: 480 }, ["스윙칩"], "high"),
  f("snack-kkokkalcorn", "꼬깔콘", "간식", 30, "1봉", { calories: 510, carbsG: 58, proteinG: 5, fatG: 28, sodiumMg: 420 }, ["꼬깔콘"], "high"),
  f("snack-saeukkang", "새우깡", "간식", 30, "1봉", { calories: 500, carbsG: 56, proteinG: 7, fatG: 27, sodiumMg: 500 }, ["새우깡"], "high"),
  f("snack-kkaedori", "꾀돌이", "간식", 30, "1봉", { calories: 490, carbsG: 55, proteinG: 6, fatG: 26, sodiumMg: 460 }, ["꾀돌이"], "high"),
  f("snack-matdongsan", "맛동산", "간식", 30, "1봉", { calories: 480, carbsG: 60, proteinG: 5, fatG: 24, sodiumMg: 380, sugarG: 25 }, ["맛동산"], "high"),
  f("snack-chakchak", "착한참쌀", "간식", 30, "1봉", { calories: 470, carbsG: 62, proteinG: 4, fatG: 22, sodiumMg: 350 }, ["참쌀과자"], "high"),
  f("snack-yakgwa-mini", "미니약과", "간식", 20, "1개", { calories: 380, carbsG: 55, proteinG: 4, fatG: 15, sodiumMg: 50, sugarG: 25 }, ["약과"], "high"),
  f("snack-yugwa", "유과", "간식", 25, "1개", { calories: 420, carbsG: 58, proteinG: 4, fatG: 18, sodiumMg: 40, sugarG: 22 }, ["유과"], "high"),
  f("snack-gangjeong", "강정", "간식", 30, "1줌", { calories: 450, carbsG: 60, proteinG: 5, fatG: 20, sodiumMg: 80, sugarG: 30 }, ["강정","견과강정"], "high"),
  f("snack-injeolmi-snack", "인절미스낵", "간식", 40, "1봉", { calories: 430, carbsG: 58, proteinG: 5, fatG: 20, sodiumMg: 120, sugarG: 22 }, ["인절미과자"], "high"),
  f("snack-rice-cracker", "누룽지과자", "간식", 30, "1봉", { calories: 440, carbsG: 62, proteinG: 6, fatG: 18, sodiumMg: 350 }, ["누룽지스낵"], "high"),
  f("snack-marshmallow-pie", "마시멜로파이", "간식", 35, "1개", { calories: 400, carbsG: 55, proteinG: 4, fatG: 18, sodiumMg: 200, sugarG: 32 }, ["마시멜로"], "high"),
  f("snack-bungeobbang-red", "붕어빵(팥)", "간식", 80, "2마리", { calories: 215, carbsG: 36, proteinG: 5, fatG: 5.5, sodiumMg: 120, sugarG: 12 }, ["붕어빵","팥붕"], "high"),
  f("snack-ice-cream-bar", "메로나", "간식", 80, "1개", { calories: 180, carbsG: 24, proteinG: 2, fatG: 8, sodiumMg: 50, sugarG: 18 }, ["메로나","아이스바"], "high"),
  f("snack-ice-cream-bbang", "빵빠라", "간식", 90, "1개", { calories: 220, carbsG: 28, proteinG: 3, fatG: 11, sodiumMg: 80, sugarG: 20 }, ["빵빠라","빵빵아"], "high"),
  f("snack-ice-cream-pig", "돼지바", "간식", 80, "1개", { calories: 190, carbsG: 25, proteinG: 2.5, fatG: 9, sodiumMg: 60, sugarG: 19 }, ["돼지바"], "high"),
  f("snack-street-tteok", "떡꼬치(간식)", "간식", 80, "1꼬치", { calories: 180, carbsG: 38, proteinG: 3, fatG: 2, sodiumMg: 350 }, ["떡꼬치"], "high"),
  f("snack-kkul-tarae", "꿀타래", "간식", 20, "1줌", { calories: 400, carbsG: 80, proteinG: 2, fatG: 8, sodiumMg: 20, sugarG: 50 }, ["꿀타래"], "high"),
  f("snack-yakult", "야쿠르트", "간식", 65, "1병", { calories: 62, carbsG: 12, proteinG: 1.2, fatG: 0.1, sodiumMg: 20, sugarG: 10 }, ["야쿠르트","유산균"], "medium"),
  f("snack-viyott", "비요뜨", "간식", 150, "1컵", { calories: 95, carbsG: 14, proteinG: 3, fatG: 3, sodiumMg: 80, sugarG: 12 }, ["비요뜨","요구르트"], "medium"),
  f("snack-custard-bun", "크림빵", "간식", 80, "1개", { calories: 310, carbsG: 42, proteinG: 6, fatG: 13, sodiumMg: 220, sugarG: 18 }, ["크림빵","베이커리"], "high"),
  f("snack-red-bean-bun", "단팥빵", "간식", 80, "1개", { calories: 280, carbsG: 48, proteinG: 6, fatG: 6, sodiumMg: 200, sugarG: 20 }, ["단팥빵"], "high"),
  f("snack-egg-bun", "소보로빵", "간식", 70, "1개", { calories: 340, carbsG: 44, proteinG: 6, fatG: 16, sodiumMg: 280, sugarG: 15 }, ["소보로"], "high"),
  f("drink-americano-ice", "아이스아메리카노", "음료", 350, "1잔", { calories: 2, carbsG: 0, proteinG: 0.3, fatG: 0, sodiumMg: 5 }, ["아아","아이스아메"], "low"),
  f("drink-latte-ice", "아이스라떼", "음료", 400, "1잔", { calories: 45, carbsG: 5, proteinG: 2.8, fatG: 2.2, sodiumMg: 45 }, ["아이스라떼"], "medium"),
  f("drink-vanilla-latte", "바닐라라떼", "음료", 400, "1잔", { calories: 75, carbsG: 12, proteinG: 2.5, fatG: 2.5, sodiumMg: 50, sugarG: 10 }, ["바닐라라떼"], "high"),
  f("drink-caramel-macchiato", "카라멜마끼아또", "음료", 400, "1잔", { calories: 68, carbsG: 10, proteinG: 2.5, fatG: 2.5, sodiumMg: 55, sugarG: 9 }, ["마끼아또"], "high"),
  f("drink-dalgona-latte", "달고나라떼", "음료", 400, "1잔", { calories: 85, carbsG: 14, proteinG: 2.5, fatG: 2.8, sodiumMg: 50, sugarG: 12 }, ["달고나라떼"], "high"),
  f("drink-strawberry-latte", "딸기라떼", "음료", 400, "1잔", { calories: 72, carbsG: 13, proteinG: 2, fatG: 2, sodiumMg: 40, sugarG: 11 }, ["딸기라떼"], "high"),
  f("drink-matcha-latte", "말차라떼", "음료", 400, "1잔", { calories: 65, carbsG: 10, proteinG: 2.5, fatG: 2.5, sodiumMg: 45, sugarG: 8 }, ["녹차라떼","말차"], "high"),
  f("drink-chocolate-latte", "초코라떼", "음료", 400, "1잔", { calories: 80, carbsG: 13, proteinG: 2.8, fatG: 2.8, sodiumMg: 50, sugarG: 11 }, ["초코라떼"], "high"),
  f("drink-coldbrew", "콜드브루", "음료", 400, "1잔", { calories: 3, carbsG: 0, proteinG: 0.3, fatG: 0, sodiumMg: 5 }, ["콜드브루"], "low"),
  f("drink-espresso", "에스프레소", "음료", 30, "1샷", { calories: 9, carbsG: 0, proteinG: 0.5, fatG: 0.2, sodiumMg: 2 }, ["에스프레소"], "low"),
  f("drink-cafemocha", "카페모카", "음료", 400, "1잔", { calories: 78, carbsG: 12, proteinG: 2.5, fatG: 3, sodiumMg: 55, sugarG: 10 }, ["모카"], "high"),
  f("drink-grapefruit-ade", "자몽에이드", "음료", 400, "1잔", { calories: 42, carbsG: 10, proteinG: 0.2, fatG: 0, sodiumMg: 10, sugarG: 9 }, ["자몽에이드","에이드"], "high"),
  f("drink-green-grape-ade", "청포도에이드", "음료", 400, "1잔", { calories: 48, carbsG: 12, proteinG: 0.2, fatG: 0, sodiumMg: 10, sugarG: 11 }, ["청포도에이드"], "high"),
  f("drink-lemon-ade", "레몬에이드", "음료", 400, "1잔", { calories: 38, carbsG: 9, proteinG: 0.2, fatG: 0, sodiumMg: 8, sugarG: 8 }, ["레몬에이드"], "high"),
  f("drink-yuja-tea", "유자차", "음료", 300, "1잔", { calories: 55, carbsG: 14, proteinG: 0.2, fatG: 0, sodiumMg: 5, sugarG: 12 }, ["유자차","유자"], "high"),
  f("drink-omija-tea", "오미자차", "음료", 300, "1잔", { calories: 40, carbsG: 10, proteinG: 0.2, fatG: 0, sodiumMg: 5, sugarG: 8 }, ["오미자차"], "high"),
  f("drink-jujube-tea", "대추차", "음료", 300, "1잔", { calories: 50, carbsG: 12, proteinG: 0.5, fatG: 0, sodiumMg: 8, sugarG: 10 }, ["대추차","대추"], "high"),
  f("drink-ginger-tea", "생강차", "음료", 300, "1잔", { calories: 35, carbsG: 8, proteinG: 0.2, fatG: 0, sodiumMg: 5, sugarG: 7 }, ["생강차","생강"], "high"),
  f("drink-citron-tea", "유자청", "음료", 300, "1잔", { calories: 60, carbsG: 15, proteinG: 0.2, fatG: 0, sodiumMg: 5, sugarG: 14 }, ["유자청"], "high"),
  f("drink-sikhye", "식혜", "음료", 300, "1잔", { calories: 55, carbsG: 13, proteinG: 0.3, fatG: 0, sodiumMg: 5, sugarG: 10 }, ["식혜"], "high"),
  f("drink-sujeonggwa", "수정과", "음료", 250, "1잔", { calories: 50, carbsG: 13, proteinG: 0.2, fatG: 0, sodiumMg: 5, sugarG: 11 }, ["수정과"], "high"),
  f("drink-misutgaru", "미숫가루", "음료", 300, "1잔", { calories: 85, carbsG: 14, proteinG: 3, fatG: 2, sodiumMg: 20, sugarG: 6 }, ["미숫가루","미숫"], "medium"),
  f("drink-banana-milk", "바나나우유", "음료", 240, "1팩", { calories: 82, carbsG: 13, proteinG: 2.5, fatG: 2.5, sodiumMg: 50, sugarG: 12 }, ["바나나우유","빙그레"], "high"),
  f("drink-strawberry-milk", "딸기우유", "음료", 240, "1팩", { calories: 78, carbsG: 12, proteinG: 2.5, fatG: 2.3, sodiumMg: 48, sugarG: 11 }, ["딸기우유"], "high"),
  f("drink-chocolate-milk", "초코우유", "음료", 240, "1팩", { calories: 85, carbsG: 13, proteinG: 2.8, fatG: 2.8, sodiumMg: 55, sugarG: 12 }, ["초코우유"], "high"),
  f("drink-vita500", "비타500", "음료", 100, "1병", { calories: 45, carbsG: 11, proteinG: 0, fatG: 0, sodiumMg: 20, sugarG: 10 }, ["비타500","비타"], "high"),
  f("drink-bacchus", "박카스", "음료", 100, "1병", { calories: 55, carbsG: 13, proteinG: 0, fatG: 0, sodiumMg: 15, sugarG: 12 }, ["박카스"], "high"),
  f("drink-hot6", "핫식스", "음료", 250, "1캔", { calories: 48, carbsG: 12, proteinG: 0, fatG: 0, sodiumMg: 80, sugarG: 11 }, ["핫식스","에너지"], "high"),
  f("drink-milkis", "밀키스", "음료", 250, "1캔", { calories: 42, carbsG: 10, proteinG: 0, fatG: 0, sodiumMg: 15, sugarG: 10 }, ["밀키스"], "high"),
  f("drink-cider-kr", "사이다", "음료", 250, "1캔", { calories: 40, carbsG: 10, proteinG: 0, fatG: 0, sodiumMg: 10, sugarG: 10 }, ["사이다","스프라이트"], "high"),
  f("drink-pocari", "포카리", "음료", 500, "1병", { calories: 26, carbsG: 6, proteinG: 0, fatG: 0, sodiumMg: 50, sugarG: 6 }, ["포카리","이온음료"], "high"),
  f("drink-boricha", "보리차", "음료", 250, "1잔", { calories: 2, carbsG: 0.5, proteinG: 0, fatG: 0, sodiumMg: 3 }, ["보리차","보리"], "low"),
  f("drink-corn-tea", "옥수수수염차", "음료", 250, "1잔", { calories: 2, carbsG: 0.4, proteinG: 0, fatG: 0, sodiumMg: 3 }, ["옥수수차"], "low"),
  f("drink-bubble-tea", "버블티", "음료", 500, "1잔", { calories: 65, carbsG: 14, proteinG: 0.5, fatG: 0.5, sodiumMg: 20, sugarG: 12 }, ["버블티","타로"], "high"),
  f("drink-brown-sugar-latte", "흑당라떼", "음료", 400, "1잔", { calories: 95, carbsG: 16, proteinG: 2.5, fatG: 2.8, sodiumMg: 45, sugarG: 14 }, ["흑당라떼","흑당"], "high"),
  f("drink-peach-ice-tea", "복숭아아이스티", "음료", 350, "1잔", { calories: 35, carbsG: 8.5, proteinG: 0, fatG: 0, sodiumMg: 15, sugarG: 8 }, ["복숭아티","아이스티"], "high"),
  f("drink-soju-flavored", "과일소주", "음료", 50, "1잔", { calories: 145, carbsG: 4, proteinG: 0, fatG: 0, sodiumMg: 2, sugarG: 3 }, ["복분자소주","자몽소주"], "high"),
  f("drink-makgeolli", "막걸리", "음료", 300, "1잔", { calories: 55, carbsG: 5, proteinG: 0.5, fatG: 0, sodiumMg: 5 }, ["막걸리","탁주"], "high"),
  f("drink-dongdongju", "동동주", "음료", 300, "1잔", { calories: 52, carbsG: 4.5, proteinG: 0.5, fatG: 0, sodiumMg: 5 }, ["동동주"], "high"),
  f("drink-cass-beer", "카스", "음료", 500, "1잔", { calories: 43, carbsG: 3.5, proteinG: 0.5, fatG: 0, sodiumMg: 4 }, ["카스","맥주"], "medium"),
  f("drink-hite-beer", "하이트", "음료", 500, "1잔", { calories: 42, carbsG: 3.4, proteinG: 0.5, fatG: 0, sodiumMg: 4 }, ["하이트"], "medium"),
  f("drink-soju-original", "소주(원본)", "음료", 50, "1잔", { calories: 130, carbsG: 0, proteinG: 0, fatG: 0, sodiumMg: 1 }, ["소주","참이슬"], "low"),
  f("drink-protein-shake-kr", "단백질음료(국내)", "음료", 250, "1팩", { calories: 55, carbsG: 5, proteinG: 8, fatG: 1, sodiumMg: 120 }, ["단백질음료","고단백"], "medium"),
  f("drink-aloe-juice", "알로에주스", "음료", 250, "1팩", { calories: 38, carbsG: 9, proteinG: 0, fatG: 0, sodiumMg: 25, sugarG: 8 }, ["알로에"], "high"),
  f("drink-tomato-juice-kr", "토마토주스", "음료", 200, "1팩", { calories: 18, carbsG: 4, proteinG: 0.8, fatG: 0.1, sodiumMg: 200, sugarG: 3 }, ["토마토주스"], "low"),
  f("drink-plum-juice", "매실주스", "음료", 200, "1잔", { calories: 42, carbsG: 10, proteinG: 0.2, fatG: 0, sodiumMg: 80, sugarG: 8 }, ["매실","매실음료"], "high"),
  f("drink-rice-drink", "식혜음료", "음료", 240, "1팩", { calories: 52, carbsG: 12, proteinG: 0.2, fatG: 0, sodiumMg: 8, sugarG: 10 }, ["쌀음료"], "high"),
]
