/** 검색용 추가 aliases — DB 항목 id → 검색어 목록 */
export const FOOD_ALIAS_PATCHES: Record<string, string[]> = {
  baeksuk: ["능이백숙", "닭백숙", "한방백숙", "누룽지백숙", "오리백숙"],
  "chicken-baeksuk": ["능이백숙", "닭백숙", "한방백숙"],
  "herbal-baeksuk": ["한방백숙", "능이백숙", "닭백숙"],
  "kimchi-jjigae": [
    "참치김치찌개",
    "돼지고기김치찌개",
    "꽁치김치찌개",
    "김치 찌개",
    "김치찌개",
  ],
  "banchan-kimchi-jjigae-ext": [
    "참치김치찌개",
    "돼지고기김치찌개",
    "꽁치김치찌개",
    "김치 찌개",
  ],
  "doenjang-soup": ["차돌된장찌개", "우렁된장찌개", "된장 찌개", "된장찌개"],
  "banchan-doenjang-jjigae": ["차돌된장찌개", "우렁된장찌개", "된장 찌개"],
  "miyeok-guk": ["소고기미역국", "조개미역국", "미역 국", "미역국"],
  "rice-fried": [
    "김치볶음밥",
    "새우볶음밥",
    "야채볶음밥",
    "계란볶음밥",
    "볶음밥",
  ],
  "rice-kimchi-fried": ["김치볶음밥", "볶음밥"],
  "rice-egg-fried": ["계란볶음밥", "볶음밥"],
  "meal-kimchi-bokkeumbap": ["김치볶음밥", "볶음밥"],
  pasta: ["파스타", "pasta", "spaghetti", "빠네"],
  "ppane-pasta": ["빠네", "ppane", "pane", "크림파스타"],
  "cream-pasta": ["빠네", "cream pasta", "크림 파스타"],
  "pasta-generic": ["파스타", "pasta", "빠네"],
  "duck-baeksuk": ["오리백숙", "백숙"],
  risotto: ["리조또", "크림리조또", "risotto"],
  "cream-risotto": ["크림리조또", "리조또", "cream risotto"],
  "chicken-breast-salad": ["닭가슴살샐러드", "닭가슴살", "샐러드"],
  "salad-chicken": ["닭가슴살샐러드", "닭가슴살", "샐러드"],
  ramen: ["치즈라면", "계란라면", "매운라면", "라면", "라면(조리)"],
  "instant-noodle": ["컵라면", "치즈라면", "계란라면", "매운라면", "라면"],
  "banchan-gukbap": ["돼지국밥", "국밥", "소고기국밥"],
  gukbap: ["돼지국밥", "소고기국밥", "순대국밥", "국밥"],
  "banchan-sundaeguk": ["순대국밥", "국밥"],
  "protein-blood-sausage-soup": ["순대국밥", "국밥"],
  kalguksu: ["바지락칼국수", "닭칼국수", "장칼국수", "칼국수"],
  "banchan-samgyetang": ["전복삼계탕", "한방삼계탕", "닭한마리", "삼계탕"],
  "meal-samgyetang-set": ["전복삼계탕", "한방삼계탕", "삼계탕"],
}
